// SPDX-License-Identifier: GPL-3.0-or-later

pragma solidity ^0.8.19;

import {IMentoRouter} from "./interfaces/IMentoRouter.sol";
import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract BrokerDemo {
    address public constant MENTO_ROUTER = 0xBE729350F8CdFC19DB6866e8579841188eE57f67;
    address public constant BI_POOL_MANAGER = 0x22d9db95E6Ae61c104A7B6F6C78D7993B94ec901;
    address public constant CUSD = 0x765DE816845861e75A25fCA122bb6898B8B1282a;
    address public constant USDC = 0xcebA9300f2b948710d2653dD7B07f33A8B32118C;
    address public constant CEUR = 0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73;

    /*
    @notice Swap CUSD for CEUR doing a two-step swap.
            Step 1. CUSD for USDC.
            Step 2. USDC for CEUR.
    @param amountIn The amount of CUSD to swap
    */
    function swapCUSDForCEUR(uint256 amountIn) public {
        // exchange ids are unique identifiers in the BiPoolManager
        // they are generated by keccak256 of the asset symbols and the exchange type
        bytes32 cusdUsdcExchangeId = keccak256(
            abi.encodePacked(
                ERC20(CUSD).symbol(),
                ERC20(USDC).symbol(),
                "ConstantSum" // pricing module name
            )
        );
        bytes32 usdcCeurExchangeId = keccak256(
            abi.encodePacked(
                ERC20(CEUR).symbol(),
                ERC20(USDC).symbol(),
                "ConstantSum" // pricing module name
            )
        );

        IMentoRouter.Step[] memory path = new IMentoRouter.Step[](2);
        path[0] = IMentoRouter.Step({
            exchangeProvider: BI_POOL_MANAGER,
            exchangeId: cusdUsdcExchangeId,
            assetIn: CUSD,
            assetOut: USDC
        });
        path[1] = IMentoRouter.Step({
            exchangeProvider: BI_POOL_MANAGER,
            exchangeId: usdcCeurExchangeId,
            assetIn: USDC,
            assetOut: CEUR
        });

        ERC20(CUSD).transferFrom(msg.sender, address(this), amountIn);
        ERC20(CUSD).approve(MENTO_ROUTER, amountIn);

        // Call the router swap function
        IMentoRouter(MENTO_ROUTER).swapExactTokensForTokens(
            amountIn,
            0, // minimum amount out
            path
        );

        ERC20(CEUR).transfer(msg.sender, ERC20(CEUR).balanceOf(address(this)));
    }
}







