// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity ^0.8.19;

import {IMentoRouter} from "./interfaces/IMentoRouter.sol";
import {IERC20Metadata} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";
// solhint-disable var-name-mixedcase
contract BrokerDemo {
    address public constant MENTO_ROUTER =
        0xBE729350F8CdFC19DB6866e8579841188eE57f67;
    address public constant BI_POOL_MANAGER =
        0x22d9db95E6Ae61c104A7B6F6C78D7993B94ec901;
    address public constant CUSD = 0x765DE816845861e75A25fCA122bb6898B8B1282a;
    address public constant USDC = 0xcebA9300f2b948710d2653dD7B07f33A8B32118C;
    address public constant CEUR = 0xD8763CBa276a3738E6DE85b4b3bF5FDed6D6cA73;

    /*
    @notice Swap CUSD for CEUR doing a two-step swap.
            Step 1. CUSD for USDC.
            Step 2. USDC for CEUR.
    @param amountIn The amount of CUSD to swap
    @param minAmountOut The minimum amount of CEUR to receive
    */
    function swapCUSDForCEUR(uint256 amountIn, uint256 minAmountOut) public {
        // exchange ids are unique identifiers in the BiPoolManager
        // they are generated by keccak256 of the asset symbols and the exchange type
        bytes32 CUSD_USDC_ExchangeId = keccak256(
            abi.encodePacked(
                IERC20Metadata(CUSD).symbol(),
                IERC20Metadata(USDC).symbol(),
                "ConstantSum" // pricing module name
            )
        );
        bytes32 USDC_CEUR_ExchangeId = keccak256(
            abi.encodePacked(
                IERC20Metadata(CEUR).symbol(),
                IERC20Metadata(USDC).symbol(),
                "ConstantSum" // pricing module name
            )
        );

        IMentoRouter.Step[] memory path = new IMentoRouter.Step[](2);
        path[0] = IMentoRouter.Step({
            exchangeProvider: BI_POOL_MANAGER,
            exchangeId: CUSD_USDC_ExchangeId,
            assetIn: CUSD,
            assetOut: USDC
        });
        path[1] = IMentoRouter.Step({
            exchangeProvider: BI_POOL_MANAGER,
            exchangeId: USDC_CEUR_ExchangeId,
            assetIn: USDC,
            assetOut: CEUR
        });

        IERC20Metadata(CUSD).transferFrom(msg.sender, address(this), amountIn);
        IERC20Metadata(CUSD).approve(MENTO_ROUTER, amountIn);

        // Call the router swap function
        IMentoRouter(MENTO_ROUTER).swapExactTokensForTokens(
            amountIn,
            minAmountOut, // minimum amount out
            path
        );

        IERC20Metadata(CEUR).transfer(
            msg.sender,
            IERC20Metadata(CEUR).balanceOf(address(this))
        );
    }
}
